### ISSUE TITLE
该组件在ios上不弹出通讯录

### ISSUE THREAD

**Issue by terraceT** [yushengchu/react-native-contacts-picker#7]
完全按照这里描述的步骤，在Android上可以正常工作，但是在iOS上不弹出通讯录，已经配置了通讯录权限。请问怎么解决？我的QQ 47493015，是否可以留下联系方式帮我解决？谢谢！

**Comment by terraceT** [comment]
没有人遇到过吗？？？

**Comment by yushengchu** [comment]
> 没有人遇到过吗？？？

参照返回的错误code是什么?
我新建的RN项目是能正常使用的

**Comment by terraceT** [comment]
哥们您好，非常感谢您能回复！
情况如下：
Toast.show('mmmmmmmmmm:', {position:20})这一句弹出来提示了，但是Toast.show('ppppppppppppp:', {position:20})这一句没有弹出，也就是说没有执行到，因此看不到result的错误码。
这个代码在Android手机上是能正常工作的，就是iOS不行。应该不是代码的问题，我感觉像是库的问题。
我的QQ是47493015 麻烦大哥帮忙解决一下，万分感谢~_~

pickContacts(onChangeText, onChangePhone)
{
    Toast.show('mmmmmmmmmm:', {position:20})
    ContactPickerBridge.openContactPicker((result) => {
        console.log('openContactPicker ---->', JSON.stringify(result));
        Toast.show('ppppppppppppp:', {position:20})
        if (result.code === 0) {
        Toast.show('kkkkkkkkkkkk:'+JSON.stringify(result.data), {position:20})
        onChangeText(result.data.name);
        onChangePhone(result.data.phone);
        }
    });
}

**Comment by yushengchu** [comment]
> 哥们您好，非常感谢您能回复！
> 情况如下：
> Toast.show（'mmmmmmmmmm：'，{position：20}）这一句弹出来提示了，但是Toast.show（'ppppppppppppp：'，{position：20} ）这一句没有弹出，也就是说没有执行到，因此看不到结果的错误码。
> 这个代码在Android的手机上是能正常工作的，就是iOS的不行。应该不是代码的问题，我感觉像是库的问题。
> 我的QQ是47493015麻烦大哥帮忙解决一下，万分感谢~_~
> 
> pickContacts（onChangeText，onChangePhone）
> { 
> Toast.show（'mmmmmmmmmm：'，{position：20}）
> ContactPickerBridge.openContactPicker（（result）=> { 
> console.log（'openContactPicker ---->'，JSON.stringify（result ））; 
> Toast.show（'ppppppppppppppp：'，{position：20}）
> if（result.code === 0）{ 
> Toast.show（'kkkkkkkkkkk：'+ JSON.stringify（result.data），{position： 20}）
> onChangeText（result.data.name）; 
> onChangePhone（result.data.phone）; 
> } 
> }）; 
> }

可能跟rn的版本也有关系 试着新建一个全新的rn项目集成看看 
附上我新建的能正常运行的项目
链接: https://pan.baidu.com/s/1eY5aOCGyGedklnO2JrBAfg 提取码: i55m

**Comment by terraceT** [comment]
您发的这个项目 报错了：
'React/RCTBridgeDelegate.h' file not found

<img width="1178" alt="屏幕快照 2019-04-12 下午12 28 03" src="https://user-images.githubusercontent.com/45414571/56012399-e9894400-5d1e-11e9-875f-342c188065db.png">

**Comment by yushengchu** [comment]
> 您发现这个项目报错了：找不到
> 'React / RCTBridgeDelegate.h'文件
> 
> <img alt="屏幕快照2019-04-12下午12 28 03" width="1178" src="https://user-images.githubusercontent.com/45414571/56012399-e9894400-5d1e-11e9-875f-342c188065db.png">

这个是RN版本的问题 这样吧 你建一个新的RN项目 重现一下问题 然后被node_modules删了打包发到网盘给我 我看看有没有问题
这个组件目前在我司的几个项目里都是正常使用的 代码上应该是没有什么问题的

**Comment by terraceT** [comment]
有问题的项目已经放到网盘上，请兄弟帮忙看看，非常感谢！
链接: https://pan.baidu.com/s/1myL5cu4XfmTHsaYw5KrFZA 提取码: qgrv

**Comment by yushengchu** [comment]
> 有问题的项目已经放到网盘上，请兄弟帮忙看看，非常感谢！
> 链接：[https](https://pan.baidu.com/s/1myL5cu4XfmTHsaYw5KrFZA)：//pan.baidu.com/s/1myL5cu4XfmTHsaYw5KrFZA提取码：qgrv

![gifLoading1](https://user-images.githubusercontent.com/9498146/56105692-1f713700-5f70-11e9-8b2f-628afe7bbf1f.gif)

我下载了你的demo 功能都是正常的
1.改成了debug的方式
2.修改AppDelegate.m中didFinishLaunchingWithOptions的实现

`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL* localUrl = [NSURL URLWithString:@"http://127.0.0.1:8081/index.bundle?platform=ios&dev=true&minify=false"];
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithBundleURL:localUrl moduleProvider:nil launchOptions:nil];
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"lease"
                                            initialProperties:nil];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  return YES;
}`

**Comment by terraceT** [comment]
按你的方式修改AppDelegate.m中didFinishLaunchingWithOptions的实现后，就启动失败了如图，改之前是连真机可以正常跑起来的。你能不修改这个地方就跑起来试下吗？
<img width="1426" alt="屏幕快照 2019-04-15 下午4 45 28" src="https://user-images.githubusercontent.com/45414571/56119262-5a8a5f00-5f9e-11e9-8516-3333bdcd33a5.png">

**Comment by yushengchu** [comment]
> 按你的方式修改AppDelegate.m中didFinishLaunchingWithOptions的实现后，就启动失败了如图，改之前是连真机可以正常跑起来的。你能不修改这个地方就跑起来试下吗？
> <img alt="屏幕快照2019-04-15下午4 45 28" width="1426" src="https://user-images.githubusercontent.com/45414571/56119262-5a8a5f00-5f9e-11e9-8516-3333bdcd33a5.png">

127.0.0.1改成电脑对应的局域网ip就能运行了..

**Comment by terraceT** [comment]
改了ip是可以运行了，但是点击按钮 还是不弹出通讯录。
![不弹出通讯录](https://user-images.githubusercontent.com/45414571/56181202-0aafa480-603f-11e9-8e8d-0da82dd562d7.jpg)

**Comment by yushengchu** [comment]
> 改了ip是可以运行了，但是点击按钮还是不弹出通讯录。
> ![不弹出通讯录](https://user-images.githubusercontent.com/45414571/56181202-0aafa480-603f-11e9-8e8d-0da82dd562d7.jpg)

这个我不清楚了.我真机跟模拟器都是能正常运行的 这个组件在已有项目里的使用也都是正常的

**Comment by terraceT** [comment]
我换了一个Mac电脑试了下，还是这样的现象。看来不是我一个人有这个问题。请帮忙加我QQ 47493015 远程支援一下，万分感谢！！！
